GET http://localhost:3000/user HTTP/1.1


### 

POST  http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
    "name": "쥐순"
}

###
PATCH  http://localhost:3000/user/1 HTTP/1.1
Content-Type: application/json

{
    "name": "콩순"
}

### TODO: PUT 메서드 수정 및 추가 
PUT http://localhost:3000/user HTTP/1.1
Content-Type: application/json
{
    "id": 0,
    "name": "김전체"
}

###
DELETE http://localhost:3000/user/6 HTTP/1.1
