### 유저 추가
POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
    "id": 4,
    "twtId": "@test",
    "name":"test"

}
### 전체 유저 목록 가져오기
GET http://localhost:3000/user/list HTTP/1.1

### 유저 한 명 데이터 가져오기
GET http://localhost:3000/user/2 HTTP/1.1

### 유저 한 명 삭제하기
DELETE http://localhost:3000/user/1 HTTP/1.1

### 유저 한 명의 데이터중 트위터 아이디만 수정하기
PUT http://localhost:3000/user/2 HTTP/1.1
Content-Type: application/json

{
    "twtId":"@leejaehoon__",
}
### 유저 한 명의 데이터중 트위터 아이디와 이름을 수정하기
PATCH http://localhost:3000/user/2 HTTP/1.1
Content-Type: application/json

{
    "twtId":"@leejaehoon__",
    "name":"jay"
}